//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pskRESTServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Id { get; set; }
        public string TripName { get; set; }
        public Nullable<System.DateTime> TripDate { get; set; }
        public int FromOfficeId { get; set; }
        public int ToOfficeId { get; set; }
    }
}
